import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider with ChangeNotifier {
  String _currentLanguage = 'en';
  
  String get currentLanguage => _currentLanguage;

  LanguageProvider() {
    _loadLanguage();
  }

  Future<void> _loadLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString('app_language') ?? 'en';
    notifyListeners();
  }

  Future<void> setLanguage(String langCode) async {
    _currentLanguage = langCode;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_language', langCode);
    notifyListeners();
  }

  String translate(String key) {
    if (_translations[_currentLanguage] != null && _translations[_currentLanguage]![key] != null) {
      return _translations[_currentLanguage]![key]!;
    }
    // Fallback to English
    return _translations['en']![key] ?? key;
  }

  final Map<String, Map<String, String>> _translations = {
    'en': {
      'hi': 'Hi',
      'feeling_today': 'How are you feeling today?',
      'check_in': 'Check in',
      'sahana_intro': "I'm Sahana.",
      'sahana_start': "Let's get started with a quick mood check.",
      'feeling_lonely': 'Feeling Lonely ?',
      'bio_feedback_test': 'Bio-Feedback Test',
      'bio_feedback_desc': 'Complete a small assessment using your camera, mic, and sensors to track your mental health status.',
      'start_assessment': 'Start Assessment',
      'mental_health_assessment': 'Mental Health Assessment',
      'phq9_desc': 'Answer a quick 9-question PHQ-9 survey to monitor your depression level.',
      'start_phq9': 'Start PHQ-9 Assessment',
      'typing_rhythm_test': 'Typing Rhythm Test',
      'typing_rhythm_desc': 'A simple typing test to analyze your stress levels through your keystroke patterns.',
      'start_typing': 'Start Typing Test',
      'energy_trend': "This week's energy trend:",
      'steady': 'Steady',
      'home': 'Home',
      'instructions': 'Instructions',
      'notifications': 'Notifications',
      'profile': 'Profile',
      'login': 'Login',
      'signup': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'username': 'Username',
      'phone_number': 'Phone Number',
      'twitter_username': 'Twitter Username (Optional)',
      'submit': 'Submit',
      'welcome_back': 'Welcome Back!',
      'edu_journey': "Let's continue your educational journey!",
      'enter_email': 'Enter your student email',
      'enter_password': 'Enter your password',
      'please_enter_email': 'Please enter your email',
      'please_enter_valid_email': 'Please enter a valid email',
      'please_enter_password': 'Please enter your password',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'create_account': 'Create Account',
      'join_us': 'Join us to start your journey!',
      'enter_username': 'Enter your username',
      'enter_phone': 'Enter your mobile number',
      'please_enter_username': 'Please enter a username',
      'please_enter_phone': 'Please enter your mobile number',
      'username_min_length': 'Username must be at least 3 characters',
      'confirm_password': 'Confirm Password',
      'confirm_your_password': 'Confirm your password',
      'please_confirm_password': 'Please confirm your password',
      'passwords_dont_match': 'Passwords do not match',
      'password_min_length': 'Password must be at least 6 characters',
      'enter_twitter': 'Enter your Twitter username (e.g., @username)',
      'question': 'Question',
      'assessment_result': 'Assessment Result',
      'severity': 'Severity',
      'finish': 'Finish',
      'typing_diagnostic': 'Typing Diagnostic',
      'typing_pattern_test': 'Typing Pattern Test',
      'typing_instruction': 'Please type the following paragraph in the box below as naturally as possible. This helps us analyze your typing rhythm for stress markers.',
      'start_typing_here': 'Start typing here...',
      'submit_analysis': 'Submit Analysis',
      'analysis_complete': 'Analysis Complete',
      'assessment_submitted': 'Assessment Submitted',
      'please_type_something': 'Please type something before submitting',
      'error_analyze_typing': 'Error: Could not analyze typing data',
      'stress_level': 'Stress Level',
      'typing_speed': 'Typing Speed',
      'user_details': 'User Details',
      'user_id': 'User ID',
      'account_type': 'Account Type',
      'admin': 'Admin',
      'regular_user': 'User',
      'mental_health_profile': 'Mental Health Profile',
      'total_sessions': 'Total Sessions',
      'avg_depression_score': 'Average Depression Score',
      'risk_factors': 'Risk Factors',
      'logout_confirm_title': 'Logout',
      'logout_confirm_msg': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'risk_level': 'Risk Level',
      'welcome_sahana': 'Welcome to Sahana!',
      'getting_started': 'Getting Started',
      'daily_mood_checkin': 'Daily Mood Check-in',
      'chatting_sahana': 'Chatting with Sahana',
      'making_calls': 'Making Calls',
      'privacy_safety': 'Privacy & Safety',
      'tips_best_experience': 'Tips for Best Experience',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'this_week': 'This Week',
      'excited': 'Excited',
      'happy': 'Happy',
      'calm': 'Calm',
      'neutral': 'Neutral',
      'anxious': 'Anxious',
      'sad': 'Sad',
      'hi_im_sahana': "Hi, I'm Sahana",
      'chat_with_me': 'Chat with me',
      'start_call': 'Start a call',
      'failed_start_call': 'Failed to start call',
      'mind_hint': "Tell me what's on your mind...",
      'sahana_listen': 'SAHANA is here to listen to you,\nHow are you feeling right now?',
      'risk': 'Risk',
      'bio_feedback_assessment': 'Bio-Feedback Assessment',
      'bio_feedback_heading': 'Check Your Depression Level',
      'stress_risk': 'Stress Risk',
      'facial_emotion': 'Facial Emotion',
      'physical_activity': 'Physical Activity',
      'heart_rate_status': 'Heart Rate Status',
      'ready_start_assessment': 'Ready to start assessment',
      'recording_sensors': 'Keep steady. Recording sensors...',
      'recording': 'Recording...',
      'analyzing_data': 'Analyzing data...',
      'assessment_complete_msg': 'Assessment Complete!',
      'bio_feedback_success': 'Bio-feedback analyzed and saved successfully.',
      'analysis_failed': 'Analysis Failed',
      'connection_error': 'Connection Error',
      'start_10s_assessment': 'Start 10s Assessment',
      'bio_data_collection_desc': 'We will collect Movement, Heart Rate, Voice, and Facial Expression data.',
      'calls': 'Calls',
      'new_call': 'New Call',
      'history': 'History',
      'start_a_call': 'Start a Call',
      'practice_ai': 'AI Practice Call',
      'practice_ai_desc': 'Practice speaking with our AI assistant',
      'call_counselor': 'Call a Counselor',
      'connect_counselor_desc': 'Connect with a professional counselor',
      'emergency_call': 'Emergency Call',
      'emergency_desc': 'Immediate support in crisis situations',
      'no_call_history': 'No call history',
      'duration': 'Duration',
      'status': 'Status',
      'days_ago': 'days ago',
      'no_counselors': 'No counselors available at the moment',
      'select_counselor': 'Select a Counselor',
      'counselor': 'Counselor',
      'languages': 'Languages',
      'failed_emergency_call': 'Failed to start emergency call',
      'emergency_confirm_msg': 'This will connect you to emergency support. Continue?',
      'chat_with_sahana': 'Chat with Sahana',
      'continue_conversation': 'Continue your conversation',
      'login_save_history': 'Login or sign up to save your chat history and continue your conversation anytime.',
      'login_continue': 'Login to Continue',
      'dont_have_account_signup': "Don't have an account? Sign up",
      'start_chatting_journey': 'Start chatting to begin your mental health journey',
      'counselor_call': 'Counselor Call',
      'ai_support_call': 'AI Support Call',
      'speaking': 'Speaking...',
      'listening': 'Listening...',
      'connected': 'Connected',
      'connecting': 'Connecting...',
      'you': 'You',
      'speech_not_available': 'Speech recognition not available on this device',
      'unmute': 'Unmute',
      'muted': 'Muted',
      'tap_to_speak': 'Tap to Speak',
      'speaker_on': 'Speaker On',
      'speaker_off': 'Speaker Off',
      'end_call': 'End Call',
      'select_language': 'Select Language',
      'voice_call_analysis': 'Voice Call Analysis',
      'language': 'Language',
      'tap_to_record': 'Tap to start recording',
      'stop_recording': 'Stop Recording',
      'start_recording': 'Start Recording',
      'analysis_results': 'Analysis Results',
      'emotion': 'Emotion',
      'depression_score': 'Depression Score',
      'bot_detected': 'Bot Detected',
      'authentic': 'Authentic',
      'bot_confidence': 'Bot Confidence',
      'bot_type': 'Bot Type',
      'transcription': 'Transcription',
      'logout': 'Logout',
      'risk_low': 'Low',
      'risk_medium': 'Medium',
      'risk_high': 'High',
      'risk_severe': 'Severe',
      'minimal': 'Minimal',
      'mild': 'Mild',
      'moderate': 'Moderate',
      'moderately_severe': 'Moderately Severe',
      'severe': 'Severe',
      'welcome_sahana_desc': 'Your mental health companion designed to support you through your journey.',
      'gs_item1': 'Complete your daily mood check-in',
      'gs_item2': 'Chat with Sahana, your AI companion',
      'gs_item3': 'Track your weekly energy trends',
      'gs_item4': 'Schedule calls with counselors when needed',
      'mood_item1': 'Select how you\'re feeling from the mood options',
      'mood_item2': 'Be honest about your current emotional state',
      'mood_item3': 'Your mood data helps Sahana understand you better',
      'mood_item4': 'Regular check-ins help track your progress',
      'chat_item1': 'Tap the Sahana icon in the bottom navigation',
      'chat_item2': 'Share your thoughts, feelings, or concerns',
      'chat_item3': 'Sahana provides empathetic responses and support',
      'chat_item4': 'Your conversations are private and secure',
      'calls_item1': 'Practice with AI for voice interactions',
      'calls_item2': 'Schedule calls with professional counselors',
      'calls_item3': 'Use emergency calls for urgent support',
      'calls_item4': 'All calls are confidential and secure',
      'privacy_item1': 'All your data is encrypted and secure',
      'privacy_item2': 'Your conversations are confidential',
      'privacy_item3': 'You can delete your data at any time',
      'privacy_item4': 'We comply with mental health data protection standards',
      'tips_item1': 'Check in daily for accurate tracking',
      'tips_item2': 'Be open and honest with Sahana',
      'tips_item3': 'Review your weekly trends regularly',
      'tips_item4': 'Reach out to counselors when needed',
      'notif_daily_checkin_title': 'Daily Check-in Reminder',
      'notif_daily_checkin_msg': 'Don\'t forget to check in with Sahana today!',
      'notif_weekly_report_title': 'Weekly Report Ready',
      'notif_weekly_report_msg': 'Your weekly mental health report is now available.',
      'notif_mood_trend_title': 'Mood Trend Update',
      'notif_mood_trend_msg': 'Your mood has been improving this week. Keep it up!',
      'notif_sahana_msg_title': 'New Message from Sahana',
      'notif_sahana_msg_msg': 'Sahana has a suggestion for you based on your recent check-ins.',
      'notif_call_rem_title': 'Call Reminder',
      'notif_call_rem_msg': 'You have a scheduled call with your counselor tomorrow.',
      'notif_wellness_tip_title': 'Wellness Tip',
      'notif_wellness_tip_msg': 'Remember to take breaks and practice mindfulness exercises.',
      'hours_ago': 'hours ago',
      'days_ago': 'days ago',
      'not_at_all': 'Not at all',
      'several_days': 'Several days',
      'more_than_half': 'More than half the days',
      'nearly_every_day': 'Nearly every day',
      'target_text': 'The quick brown fox jumps over the lazy dog. Mental health is just as important as physical health, and talking about it is the first step towards feeling better.',
    },
    'si': {
      'hi': 'හලෝ',
      'feeling_today': 'අද ඔබට කොහොමද?',
      'check_in': 'පරීක්ෂා කරන්න',
      'sahana_intro': "මම සහන.",
      'sahana_start': "අපි ඉක්මන් මනෝභාවය පරීක්ෂාවකින් ආරම්භ කරමු.",
      'feeling_lonely': 'තනිකමක් දැනෙනවාද?',
      'bio_feedback_test': 'ජෛව ප්‍රතිපෝෂණ පරීක්ෂණය',
      'bio_feedback_desc': 'ඔබේ මානසික සෞඛ්‍ය තත්ත්වය නිරීක්ෂණය කිරීම සඳහා කැමරාව, මයික්‍රොෆෝනය සහ සංවේදක භාවිතයෙන් කුඩා තක්සේරුවක් සම්පූර්ණ කරන්න.',
      'start_assessment': 'තක්සේරුව ආරම්භ කරන්න',
      'mental_health_assessment': 'මානසික සෞඛ්‍ය තක්සේරුව',
      'phq9_desc': 'ඔබේ විෂාදය මට්ටම නිරීක්ෂණය කිරීම සඳහා ඉක්මන් ප්‍රශ්න 9 ක PHQ-9 සමීක්ෂණයකට පිළිතුරු දෙන්න.',
      'start_phq9': 'PHQ-9 තක්සේරුව ආරම්භ කරන්න',
      'typing_rhythm_test': 'යතුරුලියන රිද්ම පරීක්ෂණය',
      'typing_rhythm_desc': 'ඔබේ යතුරුලියන රටා හරහා ඔබේ ආතති මට්ටම් විශ්ලේෂණය කිරීමට සරල යතුරුලියන පරීක්ෂණයක්.',
      'start_typing': 'යතුරුලියන පරීක්ෂණය ආරම්භ කරන්න',
      'energy_trend': "මෙම සතියේ ශක්ති ප්‍රවණතාවය:",
      'steady': 'ස්ථාවරයි',
      'home': 'මුල් පිටුව',
      'instructions': 'උපදෙස්',
      'notifications': 'නිවේදන',
      'profile': 'පැතිකඩ',
      'login': 'ඇතුල් වන්න',
      'signup': 'ලියාපදිංචි වන්න',
      'email': 'ඊමේල්',
      'password': 'මුරපදනය',
      'forgot_password': 'මුරපදය අමතකද?',
      'dont_have_account': "ගිණුමක් නැද්ද?",
      'already_have_account': 'දැනටමත් ගිණුමක් තිබේද?',
      'username': 'පරිශීලක නාමය',
      'phone_number': 'දුරකථන අංකය',
      'twitter_username': 'ට්විටර් නාමය (විකල්ප)',
      'submit': 'ඉදිරිපත් කරන්න',
      'welcome_back': 'නැවතත් සාදරයෙන් පිළිගනිමු!',
      'edu_journey': "අපි ඔබේ අධ්‍යාපනික ගමන දිගටම කරගෙන යමු!",
      'enter_email': 'ඔබේ ශිෂ්‍ය විද්‍යුත් තැපෑල ඇතුළත් කරන්න',
      'enter_password': 'ඔබේ මුරපදය ඇතුළත් කරන්න',
      'please_enter_email': 'කරුණාකර ඔබේ විද්‍යුත් තැපෑල ඇතුළත් කරන්න',
      'please_enter_valid_email': 'කරුණාකර වලංගු විද්‍යුත් තැපෑලක් ඇත්ළත් කරන්න',
      'please_enter_password': 'කරුණාකර ඔබේ මුරපදය ඇතුළත් කරන්න',
      'sign_in': 'ඇතුල් වන්න',
      'sign_up': 'ලියාපදිංචි වන්න',
      'create_account': 'ගිණුමක් සාදන්න',
      'join_us': 'ඔබේ ගමන ආරම්භ කිරීමට අප හා එක්වන්න!',
      'enter_username': 'ඔබේ පරිශීලක නාමය ඇතුළත් කරන්න',
      'enter_phone': 'ඔබේ දුරකථන අංකය ඇතුළත් කරන්න',
      'please_enter_username': 'කරුණාකර පරිශීලක නාමයක් ඇතුළත් කරන්න',
      'please_enter_phone': 'කරුණාකර ඔබේ දුරකථන අංකය ඇතුළත් කරන්න',
      'username_min_length': 'පරිශීලක නාමය අවම වශයෙන් අකුරු 3ක් විය යුතුය',
      'confirm_password': 'මුරපදය තහවුරු කරන්න',
      'confirm_your_password': 'ඔබේ මුරපදය තහවුරු කරන්න',
      'please_confirm_password': 'කරුණාකර ඔබේ මුරපදය තහවුරු කරන්න',
      'passwords_dont_match': 'මුරපද නොගැලපේ',
      'password_min_length': 'මුරපදය අවම වශයෙන් අකුරු 6ක් විය යුතුය',
      'enter_twitter': 'ඔබේ ට්විටර් නාමය ඇතුළත් කරන්න (උදා: @username)',
      'question': 'ප්‍රශ්නය',
      'assessment_result': 'තක්සේරු ප්‍රතිඵලය',
      'severity': 'බරපතලකම',
      'finish': 'අවසන් කරන්න',
      'typing_diagnostic': 'යතුරුලියන හඳුනාගැනීම',
      'typing_pattern_test': 'යතුරුලියන රටා පරීක්ෂණය',
      'typing_instruction': 'කරුණාකර පහත ඡේදය හැකි තරම් ස්වාභාවිකව පහත කොටුවේ ටයිප් කරන්න. මෙය ඔබගේ ආතති සලකුණු සඳහා ඔබගේ යතුරුලියන රිද්මය විශ්ලේෂණය කිරීමට අපට උපකාරී වේ.',
      'start_typing_here': 'මෙහි ටයිප් කිරීම ආරම්භ කරන්න...',
      'submit_analysis': 'විශ්ලේෂණය ඉදිරිපත් කරන්න',
      'analysis_complete': 'විශ්ලේෂණය සම්පූර්ණයි',
      'assessment_submitted': 'තක්සේරුව ඉදිරිපත් කරන ලදී',
      'please_type_something': 'කරුණාකර ඉදිරිපත් කිරීමට පෙර යමක් ටයිප් කරන්න',
      'error_analyze_typing': 'දෝෂයකි: ටයිප් කිරීමේ දත්ත විශ්ලේෂණය කිරීමට නොහැකි විය',
      'stress_level': 'ආතති මට්ටම',
      'typing_speed': 'ටයිප් කිරීමේ වේගය',
      'user_details': 'පරිශීලක විස්තර',
      'user_id': 'පරිශීලක හැඳුනුම්පත',
      'account_type': 'ගිණුම් වර්ගය',
      'admin': 'පරිපාලක',
      'regular_user': 'පරිශීලක',
      'mental_health_profile': 'මානසික සෞඛ්‍ය දැක්ම',
      'total_sessions': 'මුළු සැසි',
      'avg_depression_score': 'සාමාන්්‍ය විෂාද ලකුණු',
      'risk_factors': 'අවදානම් සාධක',
      'logout_confirm_title': 'ඉවත් වන්න',
      'logout_confirm_msg': 'ඔබට ස්ථිරවම ඉවත් වීමට අවශ්‍යද?',
      'cancel': 'අවලංගු කරන්න',
      'risk_level': 'අවදානම් මට්ටම',
      'welcome_sahana': 'සහන වෙත සාදරයෙන් පිළිගනිමු!',
      'getting_started': 'ආරම්භ කරමු',
      'daily_mood_checkin': 'දෛනික මානසික මට්ටම පරීක්ෂාව',
      'chatting_sahana': 'සහන සමඟ පිළිසඳර',
      'making_calls': 'ඇමතුම් ලබා ගැනීම',
      'privacy_safety': 'පෞද්ගලිකත්වය සහ ආරක්ෂාව',
      'tips_best_experience': 'හොඳම අත්දැකීම සඳහා උපදෙස්',
      'today': 'අද',
      'yesterday': 'ඊයේ',
      'this_week': 'මේ සතියේ',
      'excited': 'උද්‍යෝගිමත්',
      'happy': 'සතුටුයි',
      'calm': 'සන්සුන්',
      'neutral': 'සාමාන්්‍ය',
      'anxious': 'කනස්සල්ලෙන්',
      'sad': 'දුකයි',
      'hi_im_sahana': "ආයුබෝවන්, මම සහන",
      'chat_with_me': 'මා සමඟ පිළිසඳරෙහි යෙදෙන්න',
      'start_call': 'ඇමතුමක් ලබා ගන්න',
      'failed_start_call': 'ඇමතුම ලබා ගැනීමට නොහැකි විය',
      'mind_hint': 'ඔබේ සිතේ ඇති දේ මට පවසන්න...',
      'sahana_listen': 'සහන ඔබට සවන් දීමට මෙහි සිටී,\nදැන් ඔබට හැඟෙන්නේ කෙසේද?',
      'risk': 'අවදානම',
      'bio_feedback_assessment': 'ජෛව ප්‍රතිපෝෂණ තක්සේරුව',
      'bio_feedback_heading': 'ඔබේ විශාද මට්ටම පරීක්ෂා කරන්න',
      'stress_risk': 'ආතති අවදානම',
      'facial_emotion': 'මුහුණේ ඉරියව්',
      'physical_activity': 'ශාරීරික ක්‍රියාකාරකම්',
      'heart_rate_status': 'හෘද ස්පන්දන වේගය',
      'ready_start_assessment': 'තක්සේරුව ආරම්භ කිරීමට සූදානම්',
      'recording_sensors': 'සන්සුන්ව සිටින්න. සංවේදක පටිගත කරමින් පවතී...',
      'recording': 'පටිගත කරමින්...',
      'analyzing_data': 'දත්ත විශ්ලේෂණය කරමින්...',
      'assessment_complete_msg': 'තක්සේරුව සම්පූර්ණයි!',
      'bio_feedback_success': 'ජෛව ප්‍රතිපෝෂණ සාර්ථකව විශ්ලේෂණය කර සුරකින ලදී.',
      'analysis_failed': 'විශ්ලේෂණය අසාර්ථකයි',
      'connection_error': 'සම්බන්ධතා දෝෂයකි',
      'start_10s_assessment': 'තක්සේරුව ආරම්භ කරන්න (තත්පර 10)',
      'bio_data_collection_desc': 'අපි ඔබේ චලනය, හෘද ස්පන්දන වේගය, හඬ සහ මුහුණේ ඉරියව් දත්ත රැස් කරන්නෙමු.',
      'calls': 'ඇමතුම්',
      'new_call': 'නව ඇමතුම',
      'history': 'ඉතිහාසය',
      'start_a_call': 'ඇමතුමක් ආරම්භ කරන්න',
      'practice_ai_desc': 'අපගේ AI සහායකයා සමඟ කතා කිරීමට පුහුණු වන්න',
      'call_counselor': 'උපදේශකයෙකු අමතන්න',
      'connect_counselor_desc': 'වෘත්තීය උපදේශකයෙකු සමඟ සම්බන්ධ වන්න',
      'emergency_call': 'හදිසි ඇමතුම',
      'emergency_desc': 'හදිසි අවස්ථාවකදී කඩිනම් සහාය',
      'no_call_history': 'ඇමතුම් ඉතිහාසයක් නොමැත',
      'duration': 'කාලය',
      'status': 'තත්ත්වය',
      'days_ago': 'දිනකට පෙර',
      'no_counselors': 'දැනට උපදේශකයින් නොමැත',
      'select_counselor': 'උපදේශකයෙකු තෝරන්න',
      'counselor': 'උපදේශක',
      'languages': 'භාෂා',
      'failed_emergency_call': 'හදිසි ඇමතුම ලබා ගැනීමට නොහැකි විය',
      'emergency_confirm_msg': 'මෙය ඔබව හදිසි සහාය සේවාවකට සම්බන්ධ කරනු ඇත. දිගටම කරගෙන යනවාද?',
      'chat_with_sahana': 'සහන සමඟ පිළිසඳරෙහි යෙදෙන්න',
      'continue_conversation': 'ඔබේ සංවාදය දිගටම කරගෙන යන්න',
      'login_save_history': 'ඔබේ සංවාද ඉතිහාසය සුරැකීමට සහ ඕනෑම වේලාවක ඔබේ සංවාදය දිගටම කරගෙන යාමට ඇතුල් වන්න හෝ ලියාපදිංචි වන්න.',
      'login_continue': 'ඉදිරියට යාමට ඇතුල් වන්න',
      'dont_have_account_signup': "ගිණුමක් නැද්ද? ලියාපදිංචි වන්න",
      'start_chatting_journey': 'ඔබේ මානසික සෞඛ්‍ය ගමන ආරම්භ කිරීමට පිළිසඳරෙහි යෙදෙන්න',
      'counselor_call': 'උපදේශක ඇමතුම',
      'ai_support_call': 'AI සහාය ඇමතුම',
      'speaking': 'කතා කරමින්...',
      'listening': 'සවන් දෙමින්...',
      'connected': 'සම්බන්ධයි',
      'connecting': 'සම්බන්ධ වෙමින්...',
      'you': 'ඔබ',
      'speech_not_available': 'මෙම උපාංගයේ හඬ හඳුනාගැනීම ලබා ගත නොහැක',
      'unmute': 'හඬ ක්‍රියාත්මක කරන්න',
      'muted': 'නිහඬයි',
      'tap_to_speak': 'කතා කිරීමට තට්ටු කරන්න',
      'speaker_on': 'ස්පීකරය ක්‍රියාත්මකයි',
      'speaker_off': 'ස්පීකරය අක්‍රියයි',
      'end_call': 'ඇමතුම අවසන් කරන්න',
      'select_language': 'භාෂාව තෝරන්න',
      'voice_call_analysis': 'හඬ ඇමතුම් විශ්ලේෂණය',
      'language': 'භාෂාව',
      'tap_to_record': 'පටිගත කිරීම ආරම්භ කිරීමට තට්ටු කරන්න',
      'stop_recording': 'පටිගත කිරීම නවත්වන්න',
      'start_recording': 'පටිගත කිරීම ආරම්භ කරන්න',
      'analysis_results': 'විශ්ලේෂණ ප්‍රතිඵල',
      'emotion': 'චිත්තවේගය',
      'depression_score': 'විෂාද ලකුණු',
      'bot_detected': 'බෝට් හඳුනාගන්නා ලදී',
      'authentic': 'සත්‍ය',
      'bot_confidence': 'බෝට් විශ්වාසය',
      'bot_type': 'බෝට් වර්ගය',
      'transcription': 'පිටපත් කිරීම',
      'logout': 'ඉවත් වන්න',
      'risk_low': 'අඩු',
      'risk_medium': 'මධ්‍යම',
      'risk_high': 'වැඩි',
      'risk_severe': 'අධික',
      'minimal': 'අවම',
      'mild': 'මද',
      'moderate': 'මධ්‍යම',
      'moderately_severe': 'මධ්‍යම ප්‍රමාණයේ බරපතල',
      'severe': 'බරපතල',
      'welcome_sahana_desc': 'ඔබේ ගමන පුරා ඔබට සහය වීමට නිර්මාණය කර ඇති ඔබේ මානසික සෞඛ්‍ය සහකරු.',
      'gs_item1': 'ඔබේ දෛනික මනෝභාවය පරීක්ෂා කිරීම සම්පූර්ණ කරන්න',
      'gs_item2': 'ඔබේ AI සහකරු වන සහන සමඟ කතා කරන්න',
      'gs_item3': 'ඔබේ සතිපතා ශක්ති ප්‍රවණතා නිරීක්ෂණය කරන්න',
      'gs_item4': 'අවශ්‍ය අවස්ථාවලදී උපදේශකයින් සමඟ ඇමතුම් වෙන්කරවා ගන්න',
      'mood_item1': 'මනෝභාවය විකල්ප වලින් ඔබට හැඟෙන ආකාරය තෝරන්න',
      'mood_item2': 'ඔබේ වර්තමාන චිත්තවේගීය තත්ත්වය ගැන අවංක වන්න',
      'mood_item3': 'ඔබේ මනෝභාවය පිළිබඳ දත්ත සහනට ඔබව වඩා හොඳින් තේරුම් ගැනීමට උපකාරී වේ',
      'mood_item4': 'නිතිපතා පරීක්ෂා කිරීම් ඔබේ ප්‍රගතිය නිරීක්ෂණය කිරීමට උපකාරී වේ',
      'chat_item1': 'පහළ සංචාලනයේ ඇති සහන අයිකනය තට්ටු කරන්න',
      'chat_item2': 'ඔබේ සිතුවිලි, හැඟීම් හෝ ගැටළු බෙදා ගන්න',
      'chat_item3': 'සහන සහකම්පන ප්‍රතිචාර සහ සහාය ලබා දෙයි',
      'chat_item4': 'ඔබේ සංවාද පුද්ගලික සහ ආරක්ෂිතයි',
      'calls_item1': 'හඬ අන්තර්ක්‍රියා සඳහා AI සමඟ පුහුණු වන්න',
      'calls_item2': 'වෘත්තීය උපදේශකයින් සමඟ ඇමතුම් වෙන්කරවා ගන්න',
      'calls_item3': 'හදිසි සහාය සඳහා හදිසි ඇමතුම් භාවිතා කරන්න',
      'calls_item4': 'සියලුම ඇමතුම් රහස්‍ය සහ ආරක්ෂිතයි',
      'privacy_item1': 'ඔබේ සියලුම දත්ත සංකේතනය කර ආරක්ෂිතයි',
      'privacy_item2': 'ඔබේ සංවාද රහස්‍යයි',
      'privacy_item3': 'ඔබට ඕනෑම වේලාවක ඔබේ දත්ත මකා දැමිය හැකිය',
      'privacy_item4': 'අපි මානසික සෞඛ්‍ය දත්ත ආරක්ෂණ ප්‍රමිතීන්ට අනුකූල වන්නෙමු',
      'tips_item1': 'නිවැරදි නිරීක්ෂණය සඳහා දිනපතා පරීක්ෂා කරන්න',
      'tips_item2': 'සහන සමඟ විවෘතව හා අවංක වන්න',
      'tips_item3': 'ඔබේ සතිපතා ප්‍රවණතා නිතිපතා සමාලෝචනය කරන්න',
      'tips_item4': 'අවශ්‍ය වූ විට උපදේශකයින් සම්බන්ධ කරගන්න',
      'notif_daily_checkin_title': 'දෛනික පරීක්ෂා කිරීමේ මතක් කිරීම',
      'notif_daily_checkin_msg': 'අද සහන සමඟ පරීක්ෂා කිරීමට අමතක නොකරන්න!',
      'notif_weekly_report_title': 'සතිපතා වාර්තාව සූදානම්',
      'notif_weekly_report_msg': 'ඔබේ සතිපතා මානසික සෞඛ්‍ය වාර්තාව දැන් පවතී.',
      'notif_mood_trend_title': 'මනෝභාවය ප්‍රවණතා යාවත්කාලීන කිරීම',
      'notif_mood_trend_msg': 'මෙම සතියේ ඔබේ මනෝභාවය යහපත් වෙමින් පවතී. එය එසේම පවත්වා ගන්න!',
      'notif_sahana_msg_title': 'සහනගෙන් නව පණිවිඩයක්',
      'notif_sahana_msg_msg': 'ඔබේ මෑතකාලීන පරීක්ෂා කිරීම් මත පදනම්ව සහනට ඔබට උපදෙසක් ඇත.',
      'notif_call_rem_title': 'ඇමතුම් මතක් කිරීම',
      'notif_call_rem_msg': 'හෙට ඔබේ උපදේශකයා සමඟ සැලසුම් කළ ඇමතුමක් ඇත.',
      'notif_wellness_tip_title': 'සුවසාධන උපදෙස',
      'notif_wellness_tip_msg': 'විරාම ලබා ගැනීමට සහ සිහිකල්පනාවෙන් යුතුව අභ්‍යාස කිරීමට මතක තබා ගන්න.',
      'hours_ago': 'පැය වලට පෙර',
      'days_ago': 'දින වලට පෙර',
      'not_at_all': 'කිසිසේත් නැත',
      'several_days': 'දින කිහිපයක්',
      'more_than_half': 'දින අඩකට වඩා',
      'nearly_every_day': 'දිනපතාම',
      'target_text': 'කඩිසර දුඹුරු නරියා අලස බල්ලාට උඩින් පනී. මානසික සෞඛ්‍යය ශාරීරික සෞඛ්‍යය තරමටම වැදගත් වන අතර ඒ ගැන කතා කිරීම සුවපත් වීමේ පළමු පියවරයි.',
    },
    'ta': {
      'hi': 'வணக்கம்',
      'feeling_today': 'இன்று நீங்கள் எப்படி உணருகிறீர்கள்?',
      'check_in': 'சரிபார்க்கவும்',
      'sahana_intro': "நான் සහანა.",
      'sahana_start': "விரைவான மனநிலை சரிபார்ப்புடன் தொடங்குவோம்.",
      'feeling_lonely': 'தனிமையாக உணர்கிறீர்களா?',
      'bio_feedback_test': 'பயோ-ஃபீட்பேக் சோதனை',
      'bio_feedback_desc': 'உங்கள் மனநல நிலையை கண்காணிக்க உங்கள் கேமரா, மைக் மற்றும் சென்சார்களைப் பயன்படுத்தி ஒரு சிறிய மதிப்பீட்டை முடிக்கவும்.',
      'start_assessment': 'மதிப்பீட்டைத் தொடங்குங்கள்',
      'mental_health_assessment': 'மனநல மதிப்பீடு',
      'phq9_desc': 'உங்கள் மனச்சோர்வு அளவைக் கண்காணிக்க விரைவான 9-கேள்வி PHQ-9 கணக்கெடுப்பிற்கு பதிலளிக்கவும்.',
      'start_phq9': 'PHQ-9 மதிப்பீட்டைத் தொடங்குங்கள்',
      'typing_rhythm_test': 'தட்டச்சு தாள சோதனை',
      'typing_rhythm_desc': 'உங்கள் தட்டச்சு முறைகள் மூலம் உங்கள் மன அழுத்த நிலைகளை பகுப்பாய்வு செய்ய ஒரு எளிய தட்டச்சு சோதனை.',
      'start_typing': 'தட்டச்சு சோதனையைத் தொடங்குங்கள்',
      'energy_trend': "இந்த வார ஆற்றல் போக்கு:",
      'steady': 'நிலையானது',
      'home': 'முகப்பு',
      'instructions': 'அறிவுறுத்தல்கள்',
      'notifications': 'அறிவிப்புகள்',
      'profile': 'சுயவிவரம்',
      'login': 'உள்நுழைக',
      'signup': 'பதிவு செய்க',
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'forgot_password': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
      'dont_have_account': "கணக்கு இல்லையா?",
      'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா?',
      'username': 'பயனர் பெயர்',
      'phone_number': 'தொலைபேசி எண்',
      'twitter_username': 'ட்விட்டர் பயனர் பெயர் (விருப்பமானது)',
      'submit': 'சமர்ப்பிக்கவும்',
      'welcome_back': 'மீண்டும் வருக!',
      'edu_journey': "உங்கள் கல்வி பயணத்தை தொடர்வோம்!",
      'enter_email': 'உங்கள் மாணவர் மின்னஞ்சலை உள்ளிடவும்',
      'enter_password': 'உங்கள் கடவுச்சொல்லலை உள்ளிடவும்',
      'please_enter_email': 'உங்கள் மின்னஞ்சலை உள்ளிடவும்',
      'please_enter_valid_email': 'தயவுசெய்து சரியான மின்னஞ்சலை உள்ளிடவும்',
      'please_enter_password': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
      'sign_in': 'உள்நுழைக',
      'sign_up': 'பதிவு செய்க',
      'create_account': 'கணக்கை உருவாக்கு',
      'join_us': 'உங்கள் பயணத்தைத் தொடங்க எங்களுடன் இணையுங்கள்!',
      'enter_username': 'உங்கள் பயனர் பெயரை உள்ளிடவும்',
      'enter_phone': 'உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்',
      'please_enter_username': 'உங்கள் பயனர் பெயரை உள்ளிடவும்',
      'please_enter_phone': 'உங்கள் தொலைபேசி எண்ணை உள்ளிடவும்',
      'username_min_length': 'பயனர் பெயர் குறைந்தபட்சம் 3 எழுத்துக்களைக் கொண்டிருக்க வேண்டும்',
      'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'confirm_your_password': 'உங்கள் கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'please_confirm_password': 'தயவுசெய்து உங்கள் கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'passwords_dont_match': 'கடவுச்சொற்கற்கள் பொருந்தவில்லை',
      'password_min_length': 'கடவுச்சொல் குறைந்தபட்சம் 6 எழுத்துக்களைக் கொண்டிருக்க வேண்டும்',
      'enter_twitter': 'உங்கள் ட்விட்டர் பயனர் பெயரை உள்ளிடவும் (எ.கா., @username)',
      'question': 'கேள்வி',
      'assessment_result': 'மதிப்பீட்டு முடிவு',
      'severity': 'தீவிரம்',
      'finish': 'முடி',
      'typing_diagnostic': 'தட்டச்சு கண்டறிதல்',
      'typing_pattern_test': 'தட்டச்சு முறை சோதனை',
      'typing_instruction': 'தயவுசெய்து பின்வரும் பத்தியை கீழே உள்ள பெட்டியில் முடிந்தவரை இயல்பாக தட்டச்சு செய்யவும். இது மன அழுத்த குறிகாட்டிகளுக்கான உங்கள் தட்டச்சு தாளத்தை பகுப்பாய்வு செய்ய எங்களுக்கு உதவுகிறது.',
      'start_typing_here': 'இங்கே தட்டச்சு செய்யத் தொடங்குங்கள்...',
      'submit_analysis': 'பகுப்பாய்வைச் சமர்ப்பிக்கவும்',
      'analysis_complete': 'பகுப்பாய்வு முடிந்தது',
      'assessment_submitted': 'மதிப்பீடு சமர்ப்பிக்கப்பட்டது',
      'please_type_something': 'சமர்ப்பிக்கும் முன் தயவுசெய்து எதையாவது தட்டச்சு செய்யவும்',
      'error_analyze_typing': 'பிழை: தட்டச்சுத் தரவைப் பகுப்பாய்வு செய்ய முடியவில்லை',
      'stress_level': 'மன அழுத்த நிலை',
      'typing_speed': 'தட்டச்சு வேகம்',
      'user_details': 'பயனர் விவரங்கள்',
      'user_id': 'பயனர் ஐடி',
      'account_type': 'கணக்கு வகை',
      'admin': 'நிர்வாகி',
      'regular_user': 'பயனர்',
      'mental_health_profile': 'மனநல சுயவிவரம்',
      'total_sessions': 'மொத்த அமர்வுகள்',
      'avg_depression_score': 'சராசரி மனச்சோர்வு மதிப்பெண்',
      'risk_factors': 'அபாய காரணிகள்',
      'logout_confirm_title': 'வெளியேறு',
      'logout_confirm_msg': 'நீங்கள் நிச்சயமாக வெளியேறு விரும்புகிறீர்களா?',
      'cancel': 'ரத்துசெய்',
      'risk_level': 'ஆபத்து நிலை',
      'welcome_sahana': 'சஹானாவிற்கு உங்களை வரவேற்கிறோம்!',
      'getting_started': 'தொடங்குதல்',
      'daily_mood_checkin': 'தினசரி மனநிலை சரிபார்ப்பு',
      'chatting_sahana': 'சஹானாவுடன் அரட்டை',
      'making_calls': 'அழைப்புகளை மேற்கொள்ளுதல்',
      'privacy_safety': 'தனியுரிமை மற்றும் பாதுகாப்பு',
      'tips_best_experience': 'சிறந்த அனுபவத்திற்கான உதவிக்குறிப்பங்கள்',
      'today': 'இன்று',
      'yesterday': 'நேற்று',
      'this_week': 'இந்த வாரம்',
      'excited': 'உற்சாகம்',
      'happy': 'மகிழ்ச்சி',
      'calm': 'அமைதி',
      'neutral': 'சாதாரண',
      'anxious': 'பதட்டம்',
      'sad': 'சோகம்',
      'hi_im_sahana': "வணக்கம், நான் சஹானா",
      'chat_with_me': 'என்னுடன் உரையாடுங்கள்',
      'start_call': 'அழைப்பைத் தொடங்குங்கள்',
      'failed_start_call': 'அழைப்பைத் தொடங்குவதில் தோல்வி',
      'mind_hint': 'உங்கள் மனதில் இருப்பதை என்னிடம் சொல்லுங்கள்...',
      'sahana_listen': 'உங்களுக்குச் செவிசாய்க்க சஹானா இங்கே இருக்கிறாள்,\nஇப்போது நீங்கள் எப்படி உணருகிறீர்கள்?',
      'risk': 'ஆபத்து',
      'bio_feedback_assessment': 'பயோ-ஃபீட்பேக் மதிப்பீடு',
      'ready_start_assessment': 'மதிப்பீட்டைத் தொடங்கத் தயார்',
      'recording_sensors': 'அமைதியாக இருங்கள். சென்சார்கள் பதிவு செய்கின்றன...',
      'recording': 'பதிவு செய்கிறது...',
      'analyzing_data': 'தரவை பகுப்பாய்வு செய்கிறது...',
      'assessment_complete_msg': 'மதிப்பீடு முடிந்தது!',
      'bio_feedback_success': 'பயோ-ஃபீட்பேக் வெற்றிகரமாக பகுப்பாய்வு செய்யப்பட்டு சேமிக்கப்பட்டது.',
      'analysis_failed': 'பகுப்பாய்வு தோல்வியடைந்தது',
      'connection_error': 'இணைப்பு பிழை',
      'start_10s_assessment': 'மதிப்பீட்டைத் தொடங்குங்கள் (10 விநாடிகள்)',
      'bio_data_collection_desc': 'உங்கள் இயக்கம், இதயத்துடிப்பு, ஒலி மற்றும் முகபாவனை தரவுகளை நாங்கள் சேகரிப்போம்.',
      'calls': 'அழைப்புகள்',
      'new_call': 'புதிய அழைப்பு',
      'history': 'வரலாறு',
      'start_a_call': 'அழைப்பைத் தொடங்குங்கள்',
      'practice_ai_desc': 'எங்கள் AI உதவியாளருடன் பேசப் பயிற்சி செய்யுங்கள்',
      'call_counselor': 'ஆலோசனையாளரை அழைக்கவும்',
      'connect_counselor_desc': 'தொழில்முறை ஆலோசனையாளருடன் இணையுங்கள்',
      'emergency_call': 'அவசர அழைப்பு',
      'emergency_desc': 'அவசர நிலைகளில் உடனடி ஆதரவு',
      'no_call_history': 'அழைப்பு வரலாறு இல்லை',
      'duration': 'காலம்',
      'status': 'நிலை',
      'days_ago': 'நாட்களுக்கு முன்பு',
      'no_counselors': 'தற்போது ஆலோசனையாளர்கள் யாரும் இல்லை',
      'select_counselor': 'ஆலோசனையாளரைத் தேர்ந்தெடுக்கவும்',
      'counselor': 'ஆலோசனையாளர்',
      'languages': 'மொழிகள்',
      'failed_emergency_call': 'அவசர அழைப்பைத் தொடங்குவதில் தோல்வி',
      'emergency_confirm_msg': 'இது உங்களை அவசர ஆதரவுடன் இணைக்கும். தொடரவா?',
      'chat_with_sahana': 'சஹானாவுடன் உரையாடுங்கள்',
      'continue_conversation': 'உங்கள் உரையாடலைத் தொடரவும்',
      'login_save_history': 'உங்கள் அரட்டை வரலாற்றைச் சேமிக்கவும், எந்த நேரத்திலும் உங்கள் உரையாடலைத் தொடரவும் உள்நுழையவும் அல்லது பதிவு செய்யவும்.',
      'login_continue': 'தொடர உள்நுழையவும்',
      'dont_have_account_signup': "கணக்கு இல்லையா? பதிவு செய்யுங்கள்",
      'start_chatting_journey': 'உங்கள் மனநலப் பயணத்தைத் தொடங்க அரட்டையடிக்கத் தொடங்குங்கள்',
      'counselor_call': 'ஆலோசனையாளர் அழைப்பு',
      'ai_support_call': 'AI ஆதரவு அழைப்பு',
      'speaking': 'பேசுகிறது...',
      'listening': 'கேட்கிறது...',
      'connected': 'இணைக்கப்பட்டுள்ளது',
      'connecting': 'இணைக்கிறது...',
      'you': 'நீங்கள்',
      'speech_not_available': 'இந்த சாதனத்தில் பேச்சு அங்கீகாரம் கிடைக்கவில்லை',
      'unmute': 'ஒலியை இயக்கு',
      'muted': 'ஒலி முடக்கப்பட்டது',
      'tap_to_speak': 'பேச தட்டவும்',
      'speaker_on': 'ஸ்பீக்கர் ஆன்',
      'speaker_off': 'ஸ்பீக்கர் ஆஃப்',
      'end_call': 'அழைப்பை முடி',
      'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
      'voice_call_analysis': 'குரல் அழைப்பு பகுப்பாய்வு',
      'language': 'மொழி',
      'tap_to_record': 'பதிவு செய்ய தட்டவும்',
      'stop_recording': 'பதிவை நிறுத்து',
      'start_recording': 'பதிவைத் தொடங்கு',
      'analysis_results': 'பகுப்பாய்வு முடிவுகள்',
      'emotion': 'உணர்வு',
      'depression_score': 'மனச்சோர்வு மதிப்பெண்',
      'bot_detected': 'பாட் கண்டறியப்பட்டது',
      'authentic': 'உண்மையானது',
      'bot_confidence': 'பாட் நம்பிக்கை',
      'bot_type': 'பாட் வகை',
      'transcription': 'எழுத்துப்பெயர்ப்பு',
      'logout': 'வெளியேறு',
      'risk_low': 'குறைந்த',
      'risk_medium': 'நடுத்தர',
      'risk_high': 'அதிக',
      'risk_severe': 'கடுமையான',
      'minimal': 'மிகக் குறைந்த',
      'mild': 'லேசான',
      'moderate': 'மிதமான',
      'moderately_severe': 'மிதமான கடுமையான',
      'severe': 'கடுமையான',
      'welcome_sahana_desc': 'உங்கள் பயணம் முழுவதும் உங்களுக்கு ஆதரவளிக்க வடிவமைக்கப்பட்ட உங்கள் மனநலத் துணை.',
      'gs_item1': 'உங்கள் தினசரி மனநிலை சரிபார்ப்பை முடிக்கவும்',
      'gs_item2': 'உங்கள் AI உதவியாளரான சஹானாவுடன் உரையாடுங்கள்',
      'gs_item3': 'உங்கள் வாராந்திர ஆற்றல் போக்குகளைக் கண்காணிக்கவும்',
      'gs_item4': 'தேவைப்படும்போது ஆலோசனையாளர்களுடன் அழைப்புகளைத் திட்டமிடுங்கள்',
      'mood_item1': 'மனநிலை விருப்பங்களிலிருந்து நீங்கள் எப்படி உணருகிறீர்கள் என்பதைத் தேர்ந்தெடுக்கவும்',
      'mood_item2': 'உங்கள் தற்போதைய உணர்ச்சி நிலை குறித்து உண்மையாக இருங்கள்',
      'mood_item3': 'உங்கள் மனநிலைத் தரவு சஹானா உங்களை நன்றாகப் புரிந்துகொள்ள உதவுகிறது',
      'mood_item4': 'தவறாமல் சரிபார்ப்பது உங்கள் முன்னேற்றத்தைக் கண்காணிக்க உதவும்',
      'chat_item1': 'கீழ் வழிசெலுத்தலில் உள்ள சஹானா ஐகானைத் தட்டவும்',
      'chat_item2': 'உங்கள் எண்ணங்கள், உணர்வுகள் அல்லது கவலைகளைப் பகிர்ந்து கொள்ளுங்கள்',
      'chat_item3': 'சஹானா அனுதாபமான பதில்களையும் ஆதரவையும் வழங்குகிறாள்',
      'chat_item4': 'உங்கள் உரையாடல்கள் தனிப்பட்டவை மற்றும் பாதுகாப்பானவை',
      'calls_item1': 'குரல் தொடர்புகளுக்கு AI உடன் பயிற்சி செய்யுங்கள்',
      'calls_item2': 'தொழில்முறை ஆலோசனையாளர்களுடன் அழைப்புகளைத் திட்டமிடுங்கள்',
      'calls_item3': 'அவசர ஆதரவுக்கு அவசர அழைப்புகளைப் பயன்படுத்துங்கள்',
      'calls_item4': 'அனைத்து அழைப்புகளும் ரகசியமானவை மற்றும் பாதுகாப்பானவை',
      'privacy_item1': 'உங்கள் தரவு அனைத்தும் குறியாக்கம் செய்யப்பட்டு பாதுகாப்பானது',
      'privacy_item2': 'உங்கள் உரையாடல்கள் ரகசியமானவை',
      'privacy_item3': 'உங்கள் தரவை எந்த நேரத்திலும் நீக்கலாம்',
      'privacy_item4': 'நாங்கள் மனநல தரவு பாதுகாப்பு தரங்களுக்கு இணங்குகிறோம்',
      'tips_item1': 'துல்லியமான கண்காணிப்புக்கு தினமும் சரிபார்க்கவும்',
      'tips_item2': 'சஹானாவுடன் வெளிப்படையாகவும் உண்மையாகவும் இருங்கள்',
      'tips_item3': 'உங்கள் வாராந்திர போக்குகளை தவறாமல் மதிப்பாய்வு செய்யவும்',
      'tips_item4': 'தேவைப்படும்போது ஆலோசனையாளர்களைத் தொடர்பு கொள்ளுங்கள்',
      'notif_daily_checkin_title': 'தினசரி சரிபார்ப்பு நினைவூட்டல்',
      'notif_daily_checkin_msg': 'இன்று சஹானாவுடன் சரிபார்க்க மறக்காதீர்கள்!',
      'notif_weekly_report_title': 'வாராந்திர அறிக்கை தயார்',
      'notif_weekly_report_msg': 'உங்கள் வாராந்திர மனநல அறிக்கை இப்போது கிடைக்கிறது.',
      'notif_mood_trend_title': 'மனநிலை போக்கு புதுப்பிப்பு',
      'notif_mood_trend_msg': 'இந்த வாரம் உங்கள் மனநிலை மேம்பட்டு வருகிறது. அதைத் தொடருங்கள்!',
      'notif_sahana_msg_title': 'சஹானாவிடமிருந்து புதிய செய்தி',
      'notif_sahana_msg_msg': 'உங்கள் சமீபத்திய சரிபார்ப்புகளின் அடிப்படையில் சஹானா உங்களுக்கு ஒரு ஆலோசனையை வழங்குகிறாள்.',
      'notif_call_rem_title': 'அழைப்பு நினைவூட்டல்',
      'notif_call_rem_msg': 'நாளை உங்கள் ஆலோசனையாளருடன் உங்களுக்கு ஒரு அழைப்பு திட்டமிடப்பட்டுள்ளது.',
      'notif_wellness_tip_title': 'நலக் குறிப்பு',
      'notif_wellness_tip_msg': 'இடைவெளிகளை எடுக்கவும், நினைவாற்றல் பயிற்சிகளைச் செய்யவும் நினைவில் கொள்ளுங்கள்.',
      'hours_ago': 'மணிநேரத்திற்கு முன்பு',
      'days_ago': 'நாட்களுக்கு முன்பு',
      'not_at_all': 'இல்லை',
      'several_days': 'சில நாட்கள்',
      'more_than_half': 'பாதிக்கும் மேற்பட்ட நாட்கள்',
      'nearly_every_day': 'கிட்டத்தட்ட ஒவ்வொரு நாளும்',
      'target_text': 'வேகமான பழுப்பு நிற நரி சோம்பேறி நாயின் மேல் குதிக்கிறது. மன ஆரோக்கியம் உடல் ஆரோக்கியத்தைப் போலவே முக்கியமானது, அதைப் பற்றி பேசுவது நன்றாக உணருவதற்கான முதல் படியாகும்.',
    },
  };
}
