// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzOochMrKFEMqZbko8UQNlv6jMR8Bhvrw',
    appId: '1:421129802790:web:819d0a655ebafa8f9482e7',
    messagingSenderId: '421129802790',
    projectId: 'depressioin',
    authDomain: 'depressioin.firebaseapp.com',
    storageBucket: 'depressioin.firebasestorage.app',
    measurementId: 'G-9VY0DMN0XV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMHpU66PHAWdr5jGVRdWhcHDWp0tcOiI8',
    appId: '1:421129802790:android:ab6a353fa73201a69482e7',
    messagingSenderId: '421129802790',
    projectId: 'depressioin',
    storageBucket: 'depressioin.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbBUE0dxN-gFCqrwmmyBiF2EaGmJLAwAc',
    appId: '1:421129802790:ios:6b4c48fff25d4c079482e7',
    messagingSenderId: '421129802790',
    projectId: 'depressioin',
    storageBucket: 'depressioin.firebasestorage.app',
    iosBundleId: 'com.example.depressionMonitoringApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbBUE0dxN-gFCqrwmmyBiF2EaGmJLAwAc',
    appId: '1:421129802790:ios:6b4c48fff25d4c079482e7',
    messagingSenderId: '421129802790',
    projectId: 'depressioin',
    storageBucket: 'depressioin.firebasestorage.app',
    iosBundleId: 'com.example.depressionMonitoringApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzOochMrKFEMqZbko8UQNlv6jMR8Bhvrw',
    appId: '1:421129802790:web:cd3a8cc06e106d9f9482e7',
    messagingSenderId: '421129802790',
    projectId: 'depressioin',
    authDomain: 'depressioin.firebaseapp.com',
    storageBucket: 'depressioin.firebasestorage.app',
    measurementId: 'G-LZ7HDKQVBZ',
  );
}
